### ISSUE TITLE
Explain "Good for when developing iOS web content stored locally"

### ISSUE THREAD

**Issue by netpoetica** [jofan/get-file#1]
Hello,

I am just curious what your findings were here that led you to conclude this and to make this lib. Do you have any links to resources describing specific issues with iOS local files?

I am curious because I have had issues with native JS on iOS when dealing with the file:// protocol myself, and aside from what I see in the code, would just like to know what your problems/solutions were. It looks like instead of searching for a 200, you're searching for a range between 200 through 300, for example. 

Thanks for this lib!

**Comment by jofan** [comment]
Wow, totally missed this. Sorry.

The main issue was with successful HttpRequests returning status 0 from the file system, which is what content in a UIWebView is considered as. There is also checks to make sure anything in the 200-range is considered success. Lastly the check is successful if a "Not Modified" response is given.
